# Web Server Configuration Pipeline
server.port=8080

# Database Connection Integration Mapping Configurations
spring.datasource.url=jdbc:mysql://localhost:3306/parking_sys?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Framework Hibernate Lifecycle Configurations Mapping Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
